#!/usr/bin/env bash
# Renames every photo in images/Photos to activiteit1, activiteit2, ... (keeping
# each file's extension), removes exact duplicate files, and regenerates
# js/gallery-data.js so fotos.html always lists the current photos.
#
# Run this any time photos are added/removed/replaced in images/Photos:
#   ./scripts/update-gallery.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PHOTOS_DIR="$REPO_ROOT/images/Photos"
DATA_FILE="$REPO_ROOT/js/gallery-data.js"

if [[ ! -d "$PHOTOS_DIR" ]]; then
  echo "Photos directory not found: $PHOTOS_DIR" >&2
  exit 1
fi

cd "$PHOTOS_DIR"

# 1. Remove exact duplicate files (same content), keeping the first one found.
declare -A seen_hashes
while IFS= read -r -d '' f; do
  hash=$(md5sum -- "$f" | cut -d' ' -f1)
  if [[ -n "${seen_hashes[$hash]:-}" ]]; then
    rm -- "$f"
  else
    seen_hashes[$hash]="$f"
  fi
done < <(find . -maxdepth 1 -type f -print0 | sort -z)

# 2. Rename remaining files to temporary names to avoid collisions mid-rename.
i=1
while IFS= read -r -d '' f; do
  ext="${f##*.}"
  mv -- "$f" "__tmp_${i}.${ext,,}"
  i=$((i + 1))
done < <(find . -maxdepth 1 -type f ! -name '__tmp_*' -print0 | sort -z)

# 3. Rename temp files to their final activiteitN.ext names.
while IFS= read -r -d '' f; do
  base="${f#./}"
  num=$(echo "$base" | grep -oP '(?<=__tmp_)\d+')
  ext="${base##*.}"
  mv -- "$f" "activiteit${num}.${ext}"
done < <(find . -maxdepth 1 -type f -name '__tmp_*' -print0)

# 4. Regenerate js/gallery-data.js listing the final files in order.
{
  echo "// Auto-generated by scripts/update-gallery.sh - do not edit by hand."
  echo "window.galleryPhotos = ["
  i=1
  while IFS= read -r -d '' f; do
    name="${f#./}"
    echo "  { src: \"images/Photos/${name}\", alt: \"Chiro activiteit foto ${i}\" },"
    i=$((i + 1))
  done < <(find . -maxdepth 1 -type f -name 'activiteit*' -print0 | sort -zV)
  echo "];"
} > "$DATA_FILE"

count=$(find "$PHOTOS_DIR" -maxdepth 1 -type f -name 'activiteit*' | wc -l)
echo "Done: $count photo(s) renamed, $DATA_FILE regenerated."
